CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT,
    fingerprint_template BLOB,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

