#ifndef DIGITALPERSONA_GLOBAL_H
#define DIGITALPERSONA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIGITALPERSONA_LIBRARY)
#  define DIGITALPERSONA_EXPORT Q_DECL_EXPORT
#else
#  define DIGITALPERSONA_EXPORT Q_DECL_IMPORT
#endif

#endif // DIGITALPERSONA_GLOBAL_H

